package projecteulersolutions;

/*
Pentagonal numbers are generated by the formula Pn = n(3n-1)/2. The first ten are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference
are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
 */
public class Problem0044 extends Problem {

    @Override
    public boolean isSolved() {
        return false;
    }

    @Override
    public void printSolution() {
        int D = 0;
        int pj, pk;
        
        for(int j = 1; j < 100; j++) {
            for(int k = j; k < 100; k++) {
                pj = getPentagon(j);
                pk = getPentagon(k);
                int newD = (int) Math.abs(pj - pk);
                if(newD < D) {
                    D = newD;
                }
            }
        }
        
        System.out.println("The smallest difference between the pentagonal pair is " + D);
    }

    private int getPentagon(int n) {
        return n * (3 * n - 1) / 2;
    }
}
