package projecteulersolutions;

import java.util.ArrayList;

/*
Pentagonal numbers are generated by the formula Pn = n(3n-1)/2. The first ten are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference
are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
 */
public class Problem0044 extends Problem {

    @Override
    public boolean isSolved() {
        return false;
    }

    @Override
    public void printSolution() {
        System.out.println(getPentPairSolution());
    }
    
    private String getPentPairSolution() {
        ArrayList<Integer> pentList = new java.util.ArrayList<>();
        
        for(int i = 1; i > 0; i++) {
            int currPent = getPentagon(i);
            for(int p : pentList) {
                int diff = Math.abs(currPent - p);
                if(isPentagonal(Math.abs(currPent + p)) && isPentagonal(diff)) {
                    return p + " and " + currPent + " are a pentagonal pair.\nThe difference is " + diff + ".";
                }
            }
            pentList.add(currPent);
        }
        return "The solution was not found.";
    }

    private int getPentagon(int n) {
        return n * (3 * n - 1) / 2;
    }

    private boolean isPentagonal(int p) {
        return (1.0 + Math.sqrt(1 + 24 * p)) % 6 == 0;
    }
}
